### ISSUE TITLE
Module import error after installation (Mac OS)

### ISSUE THREAD

**Issue by sujit** [guoyoooping/networkdevice#1]
Tried installing netdevice via pipenv (on Mac) and while running any sample scripts, coming across with an error during run time. Installation went well without throwing any errors, but still unable to figure out why the issue throws up:

***Error log***
```
* ModuleNotFoundError: No module named 'linux'
* ModuleNotFoundError: No module named 'junos'
```

**Error during running the program**
 ```
[Running] python -u "/Users/demo/Desktop/shellauto/run.py"
Traceback (most recent call last):
  File "/Users/demo/Desktop/shellauto/run.py", line 1, in <module>
    from netdevice import linux, junos
  File "/Users/demo/.local/share/virtualenvs/shellauto-aTKKgh-h/lib/python3.7/site-packages/netdevice/__init__.py", line 14, in <module>
    import linux
ModuleNotFoundError: No module named 'linux'
```

**Below is an example code:**
```python
from netdevice import linux, junos

pc = linux.LinuxDevice("ssh://user:s3cr3tp4ss@1.2.3.4")

```

**Below is the module installation log (via pipenv):**
```
pipenv install netdevice                                 shellauto-aTKKgh-h    22:23 
Installing netdevice…
Adding netdevice to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock (67af58) out of date, updating to (3f2d37)…
Locking [dev-packages] dependencies…
✔ Success!
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (67af58)!
Installing dependencies from Pipfile.lock (67af58)…
```

<br>
Kindly have a look.

**Comment by guoyoooping** [comment]
The root cause should be that netdevice didn't support python3.

After release0.53, it should works for python3.

Please retry the latest version and report the result. Thanks.

**Comment by guoyoooping** [comment]
Please feel free to reopen it if there is any issue.

**Comment by guoyoooping** [comment]
netdevice 0.53 has been released and python3 is supported. Feel free to try it!
